if(NOT DEFINED FASTEDDY_BUILD_DIR)
    message(FATAL_ERROR "FASTEDDY_BUILD_DIR is required")
endif()

if(NOT DEFINED FASTEDDY_COVERAGE_INFO_FILE)
    message(FATAL_ERROR "FASTEDDY_COVERAGE_INFO_FILE is required")
endif()

file(GLOB_RECURSE FASTEDDY_COVERAGE_ARTIFACTS
    LIST_DIRECTORIES FALSE
    "${FASTEDDY_BUILD_DIR}/*.gcda"
    "${FASTEDDY_BUILD_DIR}/*.gcov"
    "${FASTEDDY_BUILD_DIR}/*.gcov.json.gz"
)

if(FASTEDDY_COVERAGE_ARTIFACTS)
    file(REMOVE ${FASTEDDY_COVERAGE_ARTIFACTS})
endif()

file(REMOVE "${FASTEDDY_COVERAGE_INFO_FILE}")
